# Generated by Django 5.1.5 on 2025-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collected_cars',
            field=models.ManyToManyField(blank=True, related_name='collectors', to='cars.car', verbose_name='Collected Cars'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlisted_cars',
            field=models.ManyToManyField(blank=True, related_name='wishlisters', to='cars.car', verbose_name='Wishlisted Cars'),
        ),
    ]
