# Generated by Django 5.1.5 on 2025-02-28 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Series Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1968), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('number_of_cars', models.IntegerField(blank=True, null=True, verbose_name='Number of cars')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
