# Generated by Django 5.1.5 on 2025-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Series Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
    ]
