# Generated by Django 5.1.5 on 2025-02-02 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='series',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='series',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1968), django.core.validators.MaxValueValidator(2100)], verbose_name='Year'),
        ),
    ]
