# Generated by Django 5.1.5 on 2025-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_remove_series_imageurl_series_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='number_of_cars',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of cars'),
        ),
    ]
