# Generated by Django 5.1.5 on 2025-03-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_number', models.CharField(max_length=100, verbose_name='Toy number')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('series_number', models.IntegerField(verbose_name='Number in series')),
                ('is_treasure_hunt', models.BooleanField(default=False, verbose_name='Is treasure hunt')),
                ('is_super_treasure_hunt', models.BooleanField(default=False, verbose_name='Is super treasure hunt')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='series.series', verbose_name='Series')),
            ],
        ),
    ]
